## JamMin makefile for Haiku OS ##

NAME= JamApp

TYPE= APP

SRCS= TargetSettingsWin.cpp TargetConfig.cpp main.cpp LinkerSettingsView.cpp JMOpenFilePanel.cpp JamMinWindow.cpp JamMinApp.cpp JamFile.cpp IncludeSettingsView.cpp GeneralSettingsView.cpp CompilerSettingsView.cpp
RDEFS= JamMin.rdef
LIBS= be stdc++.r4 root tracker
OPTIMIZE= FULL
WARNINGS = ALL

## include makefile engine
include $(BUILDHOME)/etc/makefile-engine
